# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "virenderOptionApp"
client_id = "345036bb02d550c5462f30f5035a200d"
application_url = "https://gained-bytes-carry-ethernet.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_themes"

[auth]
redirect_urls = [
  "https://gained-bytes-carry-ethernet.trycloudflare.com/auth/callback",
  "https://gained-bytes-carry-ethernet.trycloudflare.com/auth/shopify/callback",
  "https://gained-bytes-carry-ethernet.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "virendertesting.myshopify.com"
